### ISSUE TITLE
animations not working

### ISSUE THREAD

**Issue by freddykaberuka** [freddykaberuka/portfolio#6]
animations is not working on link and on cards

**Comment by freddykaberuka** [comment]
Fixed

**Comment by medaminedev66** [comment]
Hi @freddykaberuka , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not relevant to the project: `Portfolio: application deploy`.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
